#!/usr/bin/env python
# -*- coding: utf-8 -*-

"""
File Operation Tools

Atomic function tools for workspace file management.
Thin wrappers around FileService for LLM tool usage.
"""

from typing import Union
from agents import function_tool

from app.aicore.code_executor.models import (
    FileUploadResult,
    FileDownloadResult,
    FileListResult
)
from app.aicore.code_executor.services import FileService

# Shared service instance
_file_service = FileService()


@function_tool(strict_mode=False)
async def upload_file(
    workspace_id: str, 
    filename: str, 
    content: Union[str, bytes]
) -> FileUploadResult:
    """
    Upload a file to a workspace.
    
    Files are uploaded to the workspace root directory and are available
    to code execution. Use relative paths in your code to access uploaded files.
    
    Args:
        workspace_id: Target workspace identifier
        filename: Name of the file (can include subdirectory, e.g., "data/file.csv")
        content: File content as string or bytes
        
    Returns:
        FileUploadResult containing:
        - success: True if uploaded successfully
        - file_info: FileInfo with details if successful
        - error: Error message if failed
        
    Example:
        # Upload CSV data
        csv_content = "name,age\\nAlice,25\\nBob,30"
        result = await upload_file("ws_abc123", "data.csv", csv_content)
        if result.success:
            print(f"Uploaded {result.file_info.filename} ({result.file_info.size} bytes)")
        else:
            print(f"Upload failed: {result.error}")
            
        # Upload binary file
        with open("image.png", "rb") as f:
            image_data = f.read()
        result = await upload_file("ws_abc123", "image.png", image_data)
    """
    return await _file_service.upload_file(workspace_id, filename, content)


@function_tool(strict_mode=False)
async def download_file(workspace_id: str, file_path: str) -> FileDownloadResult:
    """
    Download a file from a workspace.
    
    Downloads files that were either uploaded to the workspace or generated
    by code execution (e.g., plots, CSV files, etc.).
    
    Args:
        workspace_id: Source workspace identifier
        file_path: Path to the file relative to workspace root
        
    Returns:
        FileDownloadResult containing:
        - success: True if downloaded successfully
        - filename: The downloaded filename if successful
        - content: File content as base64-encoded string if successful
        - content_text: File content as text if it's text-based and successful
        - size: File size in bytes if successful
        - file_path: The requested file path
        - error: Error message if failed
        
    Example:
        # Download a generated plot
        result = await download_file("ws_abc123", "outputs/plot.png")
        if result.success:
            # Save the file locally
            import base64
            with open("downloaded_plot.png", "wb") as f:
                f.write(base64.b64decode(result.content))
            print(f"Downloaded {result.filename} ({result.size} bytes)")
        else:
            print(f"Download failed: {result.error}")
                
        # Download text file
        result = await download_file("ws_abc123", "outputs/results.txt")
        if result.success and result.content_text:
            print("File contents:", result.content_text)
    """
    return await _file_service.download_file(workspace_id, file_path)


@function_tool(strict_mode=False)
async def list_workspace_files(workspace_id: str) -> FileListResult:
    """
    List all files in a workspace.
    
    Shows both uploaded files and files generated by code execution.
    Useful for discovering what files are available in the workspace.
    
    Args:
        workspace_id: Workspace to list files from
        
    Returns:
        FileListResult containing:
        - success: True if listed successfully
        - workspace_id: The workspace identifier
        - files: List of FileInfo objects if successful
        - total_files: Total number of files if successful
        - total_size_bytes: Total size of all files if successful
        - error: Error message if failed
        
    Example:
        result = await list_workspace_files("ws_abc123")
        if result.success:
            print(f"Found {result.total_files} files:")
            for file in result.files:
                print(f"  {file.relative_path} ({file.size} bytes)")
        else:
            print(f"Failed to list files: {result.error}")
    """
    return await _file_service.list_workspace_files(workspace_id) 