"""Initial migration - create all tables

Revision ID: 0c8c6f5381e8
Revises: 
Create Date: 2025-06-05 10:00:50.480298

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c8c6f5381e8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=True),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('subscription_tier', sa.String(length=50), nullable=True),
    sa.Column('monthly_quota_usd', sa.Float(), nullable=True),
    sa.Column('current_usage_usd', sa.Float(), nullable=True),
    sa.Column('quota_reset_date', sa.DateTime(), nullable=True),
    sa.Column('preferred_model', sa.String(length=100), nullable=True),
    sa.Column('preferred_temperature', sa.Float(), nullable=True),
    sa.Column('preferred_max_tokens', sa.Integer(), nullable=True),
    sa.Column('timezone', sa.String(length=50), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=True),
    sa.Column('memory_enabled', sa.Boolean(), nullable=True),
    sa.Column('memory_retention_days', sa.Integer(), nullable=True),
    sa.Column('auto_memory_importance', sa.Boolean(), nullable=True),
    sa.Column('data_retention_enabled', sa.Boolean(), nullable=True),
    sa.Column('analytics_enabled', sa.Boolean(), nullable=True),
    sa.Column('extra_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_user_id'), 'users', ['user_id'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('conversations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('conversation_id', sa.String(length=36), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('model_name', sa.String(length=100), nullable=True),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('max_tokens', sa.Integer(), nullable=True),
    sa.Column('system_prompt', sa.Text(), nullable=True),
    sa.Column('memory_enabled', sa.Boolean(), nullable=True),
    sa.Column('context_window_size', sa.Integer(), nullable=True),
    sa.Column('auto_title_generation', sa.Boolean(), nullable=True),
    sa.Column('message_count', sa.Integer(), nullable=True),
    sa.Column('total_tokens_used', sa.Integer(), nullable=True),
    sa.Column('total_cost_usd', sa.Float(), nullable=True),
    sa.Column('is_pinned', sa.Boolean(), nullable=True),
    sa.Column('is_shared', sa.Boolean(), nullable=True),
    sa.Column('share_token', sa.String(length=100), nullable=True),
    sa.Column('topics', sa.JSON(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('user_rating', sa.Float(), nullable=True),
    sa.Column('quality_score', sa.Float(), nullable=True),
    sa.Column('extra_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('last_message_at', sa.DateTime(), nullable=True),
    sa.Column('archived_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('share_token')
    )
    op.create_index(op.f('ix_conversations_conversation_id'), 'conversations', ['conversation_id'], unique=True)
    op.create_index(op.f('ix_conversations_created_at'), 'conversations', ['created_at'], unique=False)
    op.create_index(op.f('ix_conversations_id'), 'conversations', ['id'], unique=False)
    op.create_index(op.f('ix_conversations_last_message_at'), 'conversations', ['last_message_at'], unique=False)
    op.create_index(op.f('ix_conversations_user_id'), 'conversations', ['user_id'], unique=False)
    op.create_table('knowledge_files',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('file_id', sa.String(length=36), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('original_filename', sa.String(length=500), nullable=False),
    sa.Column('filename', sa.String(length=500), nullable=False),
    sa.Column('file_path', sa.String(length=1000), nullable=False),
    sa.Column('file_size_bytes', sa.Integer(), nullable=False),
    sa.Column('file_type', sa.String(length=100), nullable=False),
    sa.Column('mime_type', sa.String(length=200), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('author', sa.String(length=200), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=True),
    sa.Column('processing_status', sa.String(length=50), nullable=True),
    sa.Column('processing_started_at', sa.DateTime(), nullable=True),
    sa.Column('processing_completed_at', sa.DateTime(), nullable=True),
    sa.Column('processing_error', sa.Text(), nullable=True),
    sa.Column('processing_progress', sa.Float(), nullable=True),
    sa.Column('extracted_text', sa.Text(), nullable=True),
    sa.Column('text_length', sa.Integer(), nullable=True),
    sa.Column('word_count', sa.Integer(), nullable=True),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('chunk_count', sa.Integer(), nullable=True),
    sa.Column('embedding_model', sa.String(length=100), nullable=True),
    sa.Column('embedding_dimensions', sa.Integer(), nullable=True),
    sa.Column('embeddings_generated', sa.Boolean(), nullable=True),
    sa.Column('embeddings_stored', sa.Boolean(), nullable=True),
    sa.Column('indexed_in_vector_db', sa.Boolean(), nullable=True),
    sa.Column('vector_collection_id', sa.String(length=100), nullable=True),
    sa.Column('search_enabled', sa.Boolean(), nullable=True),
    sa.Column('quality_score', sa.Float(), nullable=True),
    sa.Column('content_type', sa.String(length=100), nullable=True),
    sa.Column('is_valid', sa.Boolean(), nullable=True),
    sa.Column('validation_errors', sa.JSON(), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=True),
    sa.Column('access_level', sa.String(length=50), nullable=True),
    sa.Column('share_token', sa.String(length=100), nullable=True),
    sa.Column('folder', sa.String(length=200), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('categories', sa.JSON(), nullable=True),
    sa.Column('topics', sa.JSON(), nullable=True),
    sa.Column('view_count', sa.Integer(), nullable=True),
    sa.Column('search_count', sa.Integer(), nullable=True),
    sa.Column('reference_count', sa.Integer(), nullable=True),
    sa.Column('last_accessed_at', sa.DateTime(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('parent_file_id', sa.Integer(), nullable=True),
    sa.Column('is_latest_version', sa.Boolean(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('key_points', sa.JSON(), nullable=True),
    sa.Column('entities', sa.JSON(), nullable=True),
    sa.Column('extra_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['parent_file_id'], ['knowledge_files.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('share_token')
    )
    op.create_index(op.f('ix_knowledge_files_created_at'), 'knowledge_files', ['created_at'], unique=False)
    op.create_index(op.f('ix_knowledge_files_file_id'), 'knowledge_files', ['file_id'], unique=True)
    op.create_index(op.f('ix_knowledge_files_id'), 'knowledge_files', ['id'], unique=False)
    op.create_index(op.f('ix_knowledge_files_user_id'), 'knowledge_files', ['user_id'], unique=False)
    op.create_table('memory_preferences',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('preference_id', sa.String(length=36), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('topic', sa.String(length=200), nullable=False),
    sa.Column('context_pattern', sa.String(length=500), nullable=True),
    sa.Column('memory_enabled', sa.Boolean(), nullable=True),
    sa.Column('importance_threshold', sa.Float(), nullable=True),
    sa.Column('retention_days', sa.Integer(), nullable=True),
    sa.Column('decay_rate', sa.Float(), nullable=True),
    sa.Column('auto_categorization', sa.Boolean(), nullable=True),
    sa.Column('auto_importance_scoring', sa.Boolean(), nullable=True),
    sa.Column('auto_topic_detection', sa.Boolean(), nullable=True),
    sa.Column('capture_entities', sa.Boolean(), nullable=True),
    sa.Column('capture_facts', sa.Boolean(), nullable=True),
    sa.Column('capture_preferences', sa.Boolean(), nullable=True),
    sa.Column('capture_goals', sa.Boolean(), nullable=True),
    sa.Column('capture_experiences', sa.Boolean(), nullable=True),
    sa.Column('is_private', sa.Boolean(), nullable=True),
    sa.Column('allow_ai_learning', sa.Boolean(), nullable=True),
    sa.Column('share_with_team', sa.Boolean(), nullable=True),
    sa.Column('max_memories_per_query', sa.Integer(), nullable=True),
    sa.Column('similarity_threshold', sa.Float(), nullable=True),
    sa.Column('temporal_weight', sa.Float(), nullable=True),
    sa.Column('notify_on_memory_creation', sa.Boolean(), nullable=True),
    sa.Column('notify_on_memory_retrieval', sa.Boolean(), nullable=True),
    sa.Column('notify_on_memory_decay', sa.Boolean(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('memory_weight', sa.Float(), nullable=True),
    sa.Column('custom_prompts', sa.JSON(), nullable=True),
    sa.Column('blacklist_keywords', sa.JSON(), nullable=True),
    sa.Column('whitelist_keywords', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.Column('usage_count', sa.Integer(), nullable=True),
    sa.Column('extra_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_memory_preferences_id'), 'memory_preferences', ['id'], unique=False)
    op.create_index(op.f('ix_memory_preferences_preference_id'), 'memory_preferences', ['preference_id'], unique=True)
    op.create_index(op.f('ix_memory_preferences_topic'), 'memory_preferences', ['topic'], unique=False)
    op.create_index(op.f('ix_memory_preferences_user_id'), 'memory_preferences', ['user_id'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('message_id', sa.String(length=36), nullable=True),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('original_content', sa.Text(), nullable=True),
    sa.Column('message_type', sa.String(length=50), nullable=True),
    sa.Column('content_format', sa.String(length=20), nullable=True),
    sa.Column('model_name', sa.String(length=100), nullable=True),
    sa.Column('model_temperature', sa.Float(), nullable=True),
    sa.Column('prompt_tokens', sa.Integer(), nullable=True),
    sa.Column('completion_tokens', sa.Integer(), nullable=True),
    sa.Column('total_tokens', sa.Integer(), nullable=True),
    sa.Column('cost_usd', sa.Float(), nullable=True),
    sa.Column('user_rating', sa.Float(), nullable=True),
    sa.Column('quality_score', sa.Float(), nullable=True),
    sa.Column('is_flagged', sa.Boolean(), nullable=True),
    sa.Column('flag_reason', sa.String(length=100), nullable=True),
    sa.Column('processing_time_ms', sa.Float(), nullable=True),
    sa.Column('is_streaming', sa.Boolean(), nullable=True),
    sa.Column('stream_completed', sa.Boolean(), nullable=True),
    sa.Column('tool_calls', sa.JSON(), nullable=True),
    sa.Column('tool_results', sa.JSON(), nullable=True),
    sa.Column('importance_score', sa.Float(), nullable=True),
    sa.Column('memory_stored', sa.Boolean(), nullable=True),
    sa.Column('memory_id', sa.String(length=100), nullable=True),
    sa.Column('attachments', sa.JSON(), nullable=True),
    sa.Column('references', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('is_edited', sa.Boolean(), nullable=True),
    sa.Column('edit_count', sa.Integer(), nullable=True),
    sa.Column('parent_message_id', sa.Integer(), nullable=True),
    sa.Column('extra_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.ForeignKeyConstraint(['parent_message_id'], ['messages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_conversation_id'), 'messages', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_messages_created_at'), 'messages', ['created_at'], unique=False)
    op.create_index(op.f('ix_messages_id'), 'messages', ['id'], unique=False)
    op.create_index(op.f('ix_messages_message_id'), 'messages', ['message_id'], unique=True)
    op.create_index(op.f('ix_messages_role'), 'messages', ['role'], unique=False)
    op.create_table('cost_tracking',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tracking_id', sa.String(length=36), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=True),
    sa.Column('message_id', sa.Integer(), nullable=True),
    sa.Column('request_id', sa.String(length=100), nullable=True),
    sa.Column('service_name', sa.String(length=100), nullable=False),
    sa.Column('operation_type', sa.String(length=100), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('total_tokens', sa.Integer(), nullable=True),
    sa.Column('input_cost_usd', sa.Float(), nullable=True),
    sa.Column('output_cost_usd', sa.Float(), nullable=True),
    sa.Column('total_cost_usd', sa.Float(), nullable=True),
    sa.Column('input_price_per_token', sa.Float(), nullable=True),
    sa.Column('output_price_per_token', sa.Float(), nullable=True),
    sa.Column('pricing_model', sa.String(length=50), nullable=True),
    sa.Column('processing_time_ms', sa.Float(), nullable=True),
    sa.Column('queue_time_ms', sa.Float(), nullable=True),
    sa.Column('total_duration_ms', sa.Float(), nullable=True),
    sa.Column('request_size_bytes', sa.Integer(), nullable=True),
    sa.Column('response_size_bytes', sa.Integer(), nullable=True),
    sa.Column('is_cached', sa.Boolean(), nullable=True),
    sa.Column('cache_hit', sa.Boolean(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('error_code', sa.String(length=100), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('quality_score', sa.Float(), nullable=True),
    sa.Column('billing_period', sa.String(length=20), nullable=False),
    sa.Column('quota_type', sa.String(length=50), nullable=True),
    sa.Column('is_billable', sa.Boolean(), nullable=True),
    sa.Column('is_over_quota', sa.Boolean(), nullable=True),
    sa.Column('feature_category', sa.String(length=100), nullable=True),
    sa.Column('usage_tier', sa.String(length=50), nullable=True),
    sa.Column('is_premium_feature', sa.Boolean(), nullable=True),
    sa.Column('region', sa.String(length=50), nullable=True),
    sa.Column('client_ip', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('hourly_bucket', sa.DateTime(), nullable=True),
    sa.Column('daily_bucket', sa.DateTime(), nullable=True),
    sa.Column('weekly_bucket', sa.DateTime(), nullable=True),
    sa.Column('monthly_bucket', sa.DateTime(), nullable=True),
    sa.Column('extra_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cost_tracking_billing_period'), 'cost_tracking', ['billing_period'], unique=False)
    op.create_index(op.f('ix_cost_tracking_conversation_id'), 'cost_tracking', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_cost_tracking_created_at'), 'cost_tracking', ['created_at'], unique=False)
    op.create_index(op.f('ix_cost_tracking_daily_bucket'), 'cost_tracking', ['daily_bucket'], unique=False)
    op.create_index(op.f('ix_cost_tracking_hourly_bucket'), 'cost_tracking', ['hourly_bucket'], unique=False)
    op.create_index(op.f('ix_cost_tracking_id'), 'cost_tracking', ['id'], unique=False)
    op.create_index(op.f('ix_cost_tracking_message_id'), 'cost_tracking', ['message_id'], unique=False)
    op.create_index(op.f('ix_cost_tracking_monthly_bucket'), 'cost_tracking', ['monthly_bucket'], unique=False)
    op.create_index(op.f('ix_cost_tracking_request_id'), 'cost_tracking', ['request_id'], unique=False)
    op.create_index(op.f('ix_cost_tracking_service_name'), 'cost_tracking', ['service_name'], unique=False)
    op.create_index(op.f('ix_cost_tracking_tracking_id'), 'cost_tracking', ['tracking_id'], unique=True)
    op.create_index(op.f('ix_cost_tracking_user_id'), 'cost_tracking', ['user_id'], unique=False)
    op.create_index(op.f('ix_cost_tracking_weekly_bucket'), 'cost_tracking', ['weekly_bucket'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cost_tracking_weekly_bucket'), table_name='cost_tracking')
    op.drop_index(op.f('ix_cost_tracking_user_id'), table_name='cost_tracking')
    op.drop_index(op.f('ix_cost_tracking_tracking_id'), table_name='cost_tracking')
    op.drop_index(op.f('ix_cost_tracking_service_name'), table_name='cost_tracking')
    op.drop_index(op.f('ix_cost_tracking_request_id'), table_name='cost_tracking')
    op.drop_index(op.f('ix_cost_tracking_monthly_bucket'), table_name='cost_tracking')
    op.drop_index(op.f('ix_cost_tracking_message_id'), table_name='cost_tracking')
    op.drop_index(op.f('ix_cost_tracking_id'), table_name='cost_tracking')
    op.drop_index(op.f('ix_cost_tracking_hourly_bucket'), table_name='cost_tracking')
    op.drop_index(op.f('ix_cost_tracking_daily_bucket'), table_name='cost_tracking')
    op.drop_index(op.f('ix_cost_tracking_created_at'), table_name='cost_tracking')
    op.drop_index(op.f('ix_cost_tracking_conversation_id'), table_name='cost_tracking')
    op.drop_index(op.f('ix_cost_tracking_billing_period'), table_name='cost_tracking')
    op.drop_table('cost_tracking')
    op.drop_index(op.f('ix_messages_role'), table_name='messages')
    op.drop_index(op.f('ix_messages_message_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_created_at'), table_name='messages')
    op.drop_index(op.f('ix_messages_conversation_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_memory_preferences_user_id'), table_name='memory_preferences')
    op.drop_index(op.f('ix_memory_preferences_topic'), table_name='memory_preferences')
    op.drop_index(op.f('ix_memory_preferences_preference_id'), table_name='memory_preferences')
    op.drop_index(op.f('ix_memory_preferences_id'), table_name='memory_preferences')
    op.drop_table('memory_preferences')
    op.drop_index(op.f('ix_knowledge_files_user_id'), table_name='knowledge_files')
    op.drop_index(op.f('ix_knowledge_files_id'), table_name='knowledge_files')
    op.drop_index(op.f('ix_knowledge_files_file_id'), table_name='knowledge_files')
    op.drop_index(op.f('ix_knowledge_files_created_at'), table_name='knowledge_files')
    op.drop_table('knowledge_files')
    op.drop_index(op.f('ix_conversations_user_id'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_last_message_at'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_id'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_created_at'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_conversation_id'), table_name='conversations')
    op.drop_table('conversations')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_user_id'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
