"""update_knowledge_files_and_add_vector_collections

Revision ID: 27b034d88c8e
Revises: 51a6bbe97503
Create Date: 2025-07-03 12:36:07.441332

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '27b034d88c8e'
down_revision: Union[str, None] = '51a6bbe97503'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vector_collections',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('collection_name', sa.String(length=100), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('qdrant_url', sa.String(length=500), nullable=False),
    sa.Column('vector_size', sa.Integer(), nullable=True),
    sa.Column('distance_metric', sa.String(length=20), nullable=True),
    sa.Column('total_documents', sa.Integer(), nullable=True),
    sa.Column('total_nodes', sa.Integer(), nullable=True),
    sa.Column('total_vectors', sa.Integer(), nullable=True),
    sa.Column('embedding_model', sa.String(length=100), nullable=True),
    sa.Column('chunk_size', sa.Integer(), nullable=True),
    sa.Column('chunk_overlap', sa.Integer(), nullable=True),
    sa.Column('pipeline_config', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('last_updated', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('last_sync', sa.DateTime(timezone=True), nullable=True),
    sa.Column('health_status', sa.String(length=50), nullable=True),
    sa.Column('avg_query_time', sa.Float(), nullable=True),
    sa.Column('last_query_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total_queries', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('error_count', sa.Integer(), nullable=True),
    sa.Column('last_error', sa.DateTime(timezone=True), nullable=True),
    sa.Column('auto_sync', sa.Boolean(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.Column('is_shared', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vector_collections_collection_name'), 'vector_collections', ['collection_name'], unique=True)
    op.create_index(op.f('ix_vector_collections_created_at'), 'vector_collections', ['created_at'], unique=False)
    op.create_index('ix_vector_collections_default', 'vector_collections', ['user_id', 'is_default'], unique=False)
    op.create_index(op.f('ix_vector_collections_id'), 'vector_collections', ['id'], unique=False)
    op.create_index('ix_vector_collections_name_user', 'vector_collections', ['collection_name', 'user_id'], unique=False)
    op.create_index(op.f('ix_vector_collections_user_id'), 'vector_collections', ['user_id'], unique=False)
    op.create_index('ix_vector_collections_user_status', 'vector_collections', ['user_id', 'status'], unique=False)
    
    # Add new columns first
    op.add_column('knowledge_files', sa.Column('file_name', sa.String(length=255), nullable=False))
    op.add_column('knowledge_files', sa.Column('file_size', sa.Integer(), nullable=True))
    op.add_column('knowledge_files', sa.Column('ref_doc_id', sa.String(length=255), nullable=True))
    op.add_column('knowledge_files', sa.Column('document_hash', sa.String(length=100), nullable=True))
    op.add_column('knowledge_files', sa.Column('node_count', sa.Integer(), nullable=True))
    op.add_column('knowledge_files', sa.Column('collection_id', sa.String(length=100), nullable=True))
    op.add_column('knowledge_files', sa.Column('processing_config', sa.JSON(), nullable=True))
    op.add_column('knowledge_files', sa.Column('file_metadata', sa.JSON(), nullable=True))
    op.add_column('knowledge_files', sa.Column('error_message', sa.Text(), nullable=True))
    op.add_column('knowledge_files', sa.Column('last_accessed', sa.DateTime(timezone=True), nullable=True))
    op.add_column('knowledge_files', sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True))
    
    # Drop the foreign key constraint first (if it exists)
    try:
        op.drop_constraint('knowledge_files_parent_file_id_fkey', 'knowledge_files', type_='foreignkey')
    except Exception:
        # Constraint might not exist, continue
        pass
    
    # Now alter the column types
    op.alter_column('knowledge_files', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('knowledge_files', 'file_id',
               existing_type=sa.VARCHAR(length=36),
               type_=sa.String(length=100),
               nullable=False)
    op.alter_column('knowledge_files', 'file_path',
               existing_type=sa.VARCHAR(length=1000),
               type_=sa.String(length=500),
               existing_nullable=False)
    op.alter_column('knowledge_files', 'parent_file_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.alter_column('knowledge_files', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('knowledge_files', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    
    # Recreate the foreign key constraint with the new types
    op.create_foreign_key('knowledge_files_parent_file_id_fkey', 'knowledge_files', 'knowledge_files', ['parent_file_id'], ['id'])
    
    # Drop unique constraint and old columns
    op.drop_constraint(op.f('knowledge_files_share_token_key'), 'knowledge_files', type_='unique')
    
    # Create new indexes
    op.create_index(op.f('ix_knowledge_files_collection_id'), 'knowledge_files', ['collection_id'], unique=False)
    op.create_index('ix_knowledge_files_collection_status', 'knowledge_files', ['collection_id', 'indexed_in_vector_db'], unique=False)
    op.create_index('ix_knowledge_files_ref_doc', 'knowledge_files', ['ref_doc_id'], unique=False)
    op.create_index(op.f('ix_knowledge_files_ref_doc_id'), 'knowledge_files', ['ref_doc_id'], unique=True)
    op.create_index('ix_knowledge_files_user_status', 'knowledge_files', ['user_id', 'processing_status'], unique=False)
    
    # Drop old columns
    op.drop_column('knowledge_files', 'deleted_at')
    op.drop_column('knowledge_files', 'summary')
    op.drop_column('knowledge_files', 'processing_started_at')
    op.drop_column('knowledge_files', 'folder')
    op.drop_column('knowledge_files', 'view_count')
    op.drop_column('knowledge_files', 'access_level')
    op.drop_column('knowledge_files', 'is_public')
    op.drop_column('knowledge_files', 'search_enabled')
    op.drop_column('knowledge_files', 'tags')
    op.drop_column('knowledge_files', 'is_latest_version')
    op.drop_column('knowledge_files', 'share_token')
    op.drop_column('knowledge_files', 'validation_errors')
    op.drop_column('knowledge_files', 'word_count')
    op.drop_column('knowledge_files', 'processing_progress')
    op.drop_column('knowledge_files', 'language')
    op.drop_column('knowledge_files', 'author')
    op.drop_column('knowledge_files', 'key_points')
    op.drop_column('knowledge_files', 'file_type')
    op.drop_column('knowledge_files', 'title')
    op.drop_column('knowledge_files', 'embeddings_stored')
    op.drop_column('knowledge_files', 'embedding_dimensions')
    op.drop_column('knowledge_files', 'categories')
    op.drop_column('knowledge_files', 'topics')
    op.drop_column('knowledge_files', 'last_accessed_at')
    op.drop_column('knowledge_files', 'processing_completed_at')
    op.drop_column('knowledge_files', 'vector_collection_id')
    op.drop_column('knowledge_files', 'search_count')
    op.drop_column('knowledge_files', 'is_valid')
    op.drop_column('knowledge_files', 'original_filename')
    op.drop_column('knowledge_files', 'chunk_count')
    op.drop_column('knowledge_files', 'processing_error')
    op.drop_column('knowledge_files', 'page_count')
    op.drop_column('knowledge_files', 'version')
    op.drop_column('knowledge_files', 'quality_score')
    op.drop_column('knowledge_files', 'text_length')
    op.drop_column('knowledge_files', 'extra_metadata')
    op.drop_column('knowledge_files', 'embedding_model')
    op.drop_column('knowledge_files', 'mime_type')
    op.drop_column('knowledge_files', 'extracted_text')
    op.drop_column('knowledge_files', 'reference_count')
    op.drop_column('knowledge_files', 'filename')
    op.drop_column('knowledge_files', 'entities')
    op.drop_column('knowledge_files', 'description')
    op.drop_column('knowledge_files', 'file_size_bytes')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('knowledge_files', sa.Column('file_size_bytes', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('knowledge_files', sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('knowledge_files', sa.Column('entities', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('knowledge_files', sa.Column('filename', sa.VARCHAR(length=500), autoincrement=False, nullable=False))
    op.add_column('knowledge_files', sa.Column('reference_count', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('knowledge_files', sa.Column('extracted_text', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('knowledge_files', sa.Column('mime_type', sa.VARCHAR(length=200), autoincrement=False, nullable=False))
    op.add_column('knowledge_files', sa.Column('embedding_model', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('knowledge_files', sa.Column('extra_metadata', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('knowledge_files', sa.Column('text_length', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('knowledge_files', sa.Column('quality_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('knowledge_files', sa.Column('version', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('knowledge_files', sa.Column('page_count', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('knowledge_files', sa.Column('processing_error', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('knowledge_files', sa.Column('chunk_count', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('knowledge_files', sa.Column('original_filename', sa.VARCHAR(length=500), autoincrement=False, nullable=False))
    op.add_column('knowledge_files', sa.Column('is_valid', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('knowledge_files', sa.Column('search_count', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('knowledge_files', sa.Column('vector_collection_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('knowledge_files', sa.Column('processing_completed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('knowledge_files', sa.Column('last_accessed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('knowledge_files', sa.Column('topics', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('knowledge_files', sa.Column('categories', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('knowledge_files', sa.Column('embedding_dimensions', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('knowledge_files', sa.Column('embeddings_stored', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('knowledge_files', sa.Column('title', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.add_column('knowledge_files', sa.Column('file_type', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('knowledge_files', sa.Column('key_points', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('knowledge_files', sa.Column('author', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.add_column('knowledge_files', sa.Column('language', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
    op.add_column('knowledge_files', sa.Column('processing_progress', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('knowledge_files', sa.Column('word_count', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('knowledge_files', sa.Column('validation_errors', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('knowledge_files', sa.Column('share_token', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('knowledge_files', sa.Column('is_latest_version', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('knowledge_files', sa.Column('tags', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('knowledge_files', sa.Column('search_enabled', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('knowledge_files', sa.Column('is_public', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('knowledge_files', sa.Column('access_level', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('knowledge_files', sa.Column('view_count', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('knowledge_files', sa.Column('folder', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.add_column('knowledge_files', sa.Column('processing_started_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('knowledge_files', sa.Column('summary', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('knowledge_files', sa.Column('deleted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_index('ix_knowledge_files_user_status', table_name='knowledge_files')
    op.drop_index(op.f('ix_knowledge_files_ref_doc_id'), table_name='knowledge_files')
    op.drop_index('ix_knowledge_files_ref_doc', table_name='knowledge_files')
    op.drop_index('ix_knowledge_files_collection_status', table_name='knowledge_files')
    op.drop_index(op.f('ix_knowledge_files_collection_id'), table_name='knowledge_files')
    op.create_unique_constraint(op.f('knowledge_files_share_token_key'), 'knowledge_files', ['share_token'])
    op.alter_column('knowledge_files', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('knowledge_files', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('knowledge_files', 'parent_file_id',
               existing_type=sa.String(length=50),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('knowledge_files', 'file_path',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=1000),
               existing_nullable=False)
    op.alter_column('knowledge_files', 'file_id',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=36),
               nullable=True)
    op.alter_column('knowledge_files', 'id',
               existing_type=sa.String(length=50),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_column('knowledge_files', 'processed_at')
    op.drop_column('knowledge_files', 'last_accessed')
    op.drop_column('knowledge_files', 'error_message')
    op.drop_column('knowledge_files', 'file_metadata')
    op.drop_column('knowledge_files', 'processing_config')
    op.drop_column('knowledge_files', 'collection_id')
    op.drop_column('knowledge_files', 'node_count')
    op.drop_column('knowledge_files', 'document_hash')
    op.drop_column('knowledge_files', 'ref_doc_id')
    op.drop_column('knowledge_files', 'file_size')
    op.drop_column('knowledge_files', 'file_name')
    op.drop_index('ix_vector_collections_user_status', table_name='vector_collections')
    op.drop_index(op.f('ix_vector_collections_user_id'), table_name='vector_collections')
    op.drop_index('ix_vector_collections_name_user', table_name='vector_collections')
    op.drop_index(op.f('ix_vector_collections_id'), table_name='vector_collections')
    op.drop_index('ix_vector_collections_default', table_name='vector_collections')
    op.drop_index(op.f('ix_vector_collections_created_at'), table_name='vector_collections')
    op.drop_index(op.f('ix_vector_collections_collection_name'), table_name='vector_collections')
    op.drop_table('vector_collections')
    # ### end Alembic commands ###
