"""add_openai_files_table

Revision ID: 51a6bbe97503
Revises: 9328768c0463
Create Date: 2025-06-19 09:10:21.347833

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '51a6bbe97503'
down_revision: Union[str, None] = '9328768c0463'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('openai_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('openai_file_id', sa.String(length=255), nullable=False),
    sa.Column('filename', sa.String(length=500), nullable=False),
    sa.Column('purpose', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('file_size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('tags', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_openai_file_user', 'openai_files', ['openai_file_id', 'user_id'], unique=False)
    op.create_index('idx_purpose_status', 'openai_files', ['purpose', 'status'], unique=False)
    op.create_index('idx_user_uploaded_openai', 'openai_files', ['user_id', 'uploaded_at'], unique=False)
    op.create_index(op.f('ix_openai_files_id'), 'openai_files', ['id'], unique=False)
    op.create_index(op.f('ix_openai_files_openai_file_id'), 'openai_files', ['openai_file_id'], unique=True)
    op.create_index(op.f('ix_openai_files_purpose'), 'openai_files', ['purpose'], unique=False)
    op.create_index(op.f('ix_openai_files_user_id'), 'openai_files', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_openai_files_user_id'), table_name='openai_files')
    op.drop_index(op.f('ix_openai_files_purpose'), table_name='openai_files')
    op.drop_index(op.f('ix_openai_files_openai_file_id'), table_name='openai_files')
    op.drop_index(op.f('ix_openai_files_id'), table_name='openai_files')
    op.drop_index('idx_user_uploaded_openai', table_name='openai_files')
    op.drop_index('idx_purpose_status', table_name='openai_files')
    op.drop_index('idx_openai_file_user', table_name='openai_files')
    op.drop_table('openai_files')
    # ### end Alembic commands ###
