"""add_user_memory_system

Revision ID: 6a6840f33d36
Revises: 1aa3c8020047
Create Date: 2025-06-14 13:16:21.809558

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a6840f33d36'
down_revision: Union[str, None] = '1aa3c8020047'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_memories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('memory_id', sa.String(length=36), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('bucket', sa.String(length=50), nullable=False),
    sa.Column('memory_type', sa.String(length=50), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('structured_data', sa.JSON(), nullable=True),
    sa.Column('importance', sa.Float(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('last_accessed', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_archived', sa.Boolean(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('last_activity', sa.DateTime(), nullable=True),
    sa.Column('relationship_strength', sa.String(length=20), nullable=True),
    sa.Column('source_conversation_id', sa.String(length=36), nullable=True),
    sa.Column('source_message_id', sa.String(length=36), nullable=True),
    sa.Column('extraction_method', sa.String(length=50), nullable=True),
    sa.Column('access_count', sa.Integer(), nullable=True),
    sa.Column('last_updated_by', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_memories_bucket'), 'user_memories', ['bucket'], unique=False)
    op.create_index(op.f('ix_user_memories_created_at'), 'user_memories', ['created_at'], unique=False)
    op.create_index(op.f('ix_user_memories_expires_at'), 'user_memories', ['expires_at'], unique=False)
    op.create_index(op.f('ix_user_memories_id'), 'user_memories', ['id'], unique=False)
    op.create_index(op.f('ix_user_memories_importance'), 'user_memories', ['importance'], unique=False)
    op.create_index(op.f('ix_user_memories_is_active'), 'user_memories', ['is_active'], unique=False)
    op.create_index(op.f('ix_user_memories_last_accessed'), 'user_memories', ['last_accessed'], unique=False)
    op.create_index(op.f('ix_user_memories_memory_id'), 'user_memories', ['memory_id'], unique=True)
    op.create_index(op.f('ix_user_memories_source_conversation_id'), 'user_memories', ['source_conversation_id'], unique=False)
    op.create_index(op.f('ix_user_memories_user_id'), 'user_memories', ['user_id'], unique=False)
    op.create_index(op.f('ix_cost_tracking_user_id'), 'cost_tracking', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cost_tracking_user_id'), table_name='cost_tracking')
    op.drop_index(op.f('ix_user_memories_user_id'), table_name='user_memories')
    op.drop_index(op.f('ix_user_memories_source_conversation_id'), table_name='user_memories')
    op.drop_index(op.f('ix_user_memories_memory_id'), table_name='user_memories')
    op.drop_index(op.f('ix_user_memories_last_accessed'), table_name='user_memories')
    op.drop_index(op.f('ix_user_memories_is_active'), table_name='user_memories')
    op.drop_index(op.f('ix_user_memories_importance'), table_name='user_memories')
    op.drop_index(op.f('ix_user_memories_id'), table_name='user_memories')
    op.drop_index(op.f('ix_user_memories_expires_at'), table_name='user_memories')
    op.drop_index(op.f('ix_user_memories_created_at'), table_name='user_memories')
    op.drop_index(op.f('ix_user_memories_bucket'), table_name='user_memories')
    op.drop_table('user_memories')
    # ### end Alembic commands ###
