"""add_vector_collection_name_and_vector_docs_columns

Revision ID: 84ecbff5adaf
Revises: 27b034d88c8e
Create Date: 2025-07-03 23:12:10.236550

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '84ecbff5adaf'
down_revision: Union[str, None] = '27b034d88c8e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('vector_collection_name', sa.String(length=200), nullable=True))
    op.alter_column('knowledge_files', 'id',
               existing_type=sa.VARCHAR(length=50),
               server_default=None,
               existing_nullable=False)
    op.add_column('messages', sa.Column('vector_docs', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'vector_docs')
    op.alter_column('knowledge_files', 'id',
               existing_type=sa.VARCHAR(length=50),
               server_default=sa.text("nextval('knowledge_files_id_seq'::regclass)"),
               existing_nullable=False)
    op.drop_column('conversations', 'vector_collection_name')
    # ### end Alembic commands ###
