"""create uploaded_images table properly

Revision ID: 8e1e16a41ffe
Revises: 792bfba107fc
Create Date: 2025-06-18 20:32:45.478311

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e1e16a41ffe'
down_revision: Union[str, None] = '792bfba107fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('uploaded_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_id', sa.String(length=255), nullable=False),
    sa.Column('filename', sa.String(length=500), nullable=False),
    sa.Column('s3_key', sa.String(length=1000), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=False),
    sa.Column('file_size', sa.BigInteger(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('accessed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('tags', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('s3_key')
    )
    op.create_index('idx_file_id_user', 'uploaded_images', ['file_id', 'user_id'], unique=False)
    op.create_index('idx_user_uploaded', 'uploaded_images', ['user_id', 'uploaded_at'], unique=False)
    op.create_index(op.f('ix_uploaded_images_file_id'), 'uploaded_images', ['file_id'], unique=True)
    op.create_index(op.f('ix_uploaded_images_id'), 'uploaded_images', ['id'], unique=False)
    op.create_index(op.f('ix_uploaded_images_user_id'), 'uploaded_images', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_uploaded_images_user_id'), table_name='uploaded_images')
    op.drop_index(op.f('ix_uploaded_images_id'), table_name='uploaded_images')
    op.drop_index(op.f('ix_uploaded_images_file_id'), table_name='uploaded_images')
    op.drop_index('idx_user_uploaded', table_name='uploaded_images')
    op.drop_index('idx_file_id_user', table_name='uploaded_images')
    op.drop_table('uploaded_images')
    # ### end Alembic commands ###
