"""add thumbnail_s3_keys to uploaded_images

Revision ID: 9328768c0463
Revises: 8e1e16a41ffe
Create Date: 2025-06-18 21:13:12.729268

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9328768c0463'
down_revision: Union[str, None] = '8e1e16a41ffe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('uploaded_images', sa.Column('thumbnail_s3_keys', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('uploaded_images', 'thumbnail_s3_keys')
    # ### end Alembic commands ###
