"""change_vector_collection_scope_to_string

Revision ID: f9b3f485b279
Revises: fccd5301650c
Create Date: 2025-07-07 11:09:02.117766

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f9b3f485b279'
down_revision: Union[str, None] = 'fccd5301650c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vector_collections', sa.Column('scope', sa.String(length=50), nullable=False))
    op.add_column('vector_collections', sa.Column('scope_id', sa.String(length=50), nullable=False))
    op.create_index('ix_vector_collections_scope', 'vector_collections', ['scope', 'scope_id'], unique=False)
    op.create_index(op.f('ix_vector_collections_scope_id'), 'vector_collections', ['scope_id'], unique=False)
    op.create_index('ix_vector_collections_scope_status', 'vector_collections', ['scope', 'scope_id', 'status'], unique=False)
    op.create_index('ix_vector_collections_user_scope', 'vector_collections', ['user_id', 'scope', 'scope_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_vector_collections_user_scope', table_name='vector_collections')
    op.drop_index('ix_vector_collections_scope_status', table_name='vector_collections')
    op.drop_index(op.f('ix_vector_collections_scope_id'), table_name='vector_collections')
    op.drop_index('ix_vector_collections_scope', table_name='vector_collections')
    op.drop_column('vector_collections', 'scope_id')
    op.drop_column('vector_collections', 'scope')
    # ### end Alembic commands ###
