"""Update vector collections and knowledge files to use UUID foreign keys

Revision ID: fcaf26b886b8
Revises: f9b3f485b279
Create Date: 2025-07-07 17:32:21.159026

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fcaf26b886b8'
down_revision: Union[str, None] = 'f9b3f485b279'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Step 1: Drop foreign key constraints first (order fixed for PostgreSQL compatibility)
    op.drop_constraint(op.f('knowledge_files_user_id_fkey'), 'knowledge_files', type_='foreignkey')
    op.drop_constraint(op.f('vector_collections_user_id_fkey'), 'vector_collections', type_='foreignkey')
    
    # Step 2: Alter column types
    op.alter_column('knowledge_files', 'user_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=36),
               existing_nullable=False)
    op.alter_column('vector_collections', 'user_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=36),
               existing_nullable=False)
    
    # Step 3: Update index (autogenerated)
    op.drop_index(op.f('ix_vector_collections_scope'), table_name='vector_collections')
    op.create_index(op.f('ix_vector_collections_scope'), 'vector_collections', ['scope'], unique=False)
    
    # Step 4: Recreate foreign key constraints with new target
    op.create_foreign_key(None, 'knowledge_files', 'users', ['user_id'], ['user_id'])
    op.create_foreign_key(None, 'vector_collections', 'users', ['user_id'], ['user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Step 1: Drop foreign key constraints first (order fixed for PostgreSQL compatibility)
    op.drop_constraint(None, 'vector_collections', type_='foreignkey')
    op.drop_constraint(None, 'knowledge_files', type_='foreignkey')
    
    # Step 2: Restore index to original state (autogenerated)
    op.drop_index(op.f('ix_vector_collections_scope'), table_name='vector_collections')
    op.create_index(op.f('ix_vector_collections_scope'), 'vector_collections', ['scope', 'scope_id'], unique=False)
    
    # Step 3: Alter column types back to INTEGER
    op.alter_column('vector_collections', 'user_id',
               existing_type=sa.String(length=36),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('knowledge_files', 'user_id',
               existing_type=sa.String(length=36),
               type_=sa.INTEGER(),
               existing_nullable=False)
    
    # Step 4: Recreate foreign key constraints with original target
    op.create_foreign_key(op.f('vector_collections_user_id_fkey'), 'vector_collections', 'users', ['user_id'], ['id'])
    op.create_foreign_key(op.f('knowledge_files_user_id_fkey'), 'knowledge_files', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
