"""add_vector_file_references_to_messages

Revision ID: fccd5301650c
Revises: 27b034d88c8e
Create Date: 2025-07-03 23:34:34.501618

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fccd5301650c'
down_revision: Union[str, None] = '27b034d88c8e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('knowledge_files', 'id',
               existing_type=sa.VARCHAR(length=50),
               server_default=None,
               existing_nullable=False)
    op.add_column('messages', sa.Column('vector_file_references', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'vector_file_references')
    op.alter_column('knowledge_files', 'id',
               existing_type=sa.VARCHAR(length=50),
               server_default=sa.text("nextval('knowledge_files_id_seq'::regclass)"),
               existing_nullable=False)
    # ### end Alembic commands ###
