/**
 * Generates temporary IDs for client-side entities that will be replaced by backend UUIDs.
 * 
 * Following industry best practices:
 * - Simple timestamp + random for temporary client-side IDs
 * - No crypto dependency (works in all environments)
 * - Fast performance for high-frequency generation
 * - Clear "temp_" prefix indicates temporary nature
 * 
 * Used by React, Vue, Angular, and major tech companies for temporary state.
 */

/**
 * Generate a temporary ID for client-side entities
 * @param prefix - Optional prefix to identify the entity type (e.g., 'conv', 'msg', 'user')
 * @returns Temporary ID in format: temp_{prefix}_{timestamp}_{random}
 */
export function generateTempId(prefix: string = 'entity'): string {
  const timestamp = Date.now().toString(36); // Base36 for shorter string
  const random = Math.random().toString(36).substr(2, 9); // 9 chars of randomness
  
  return `temp_${prefix}_${timestamp}_${random}`;
}

/**
 * Generate a pair of related temporary IDs (e.g., internal ID + public ID)
 * @param prefix1 - Prefix for first ID
 * @param prefix2 - Prefix for second ID  
 * @returns Tuple of two temporary IDs
 */
export function generateTempIdPair(prefix1: string, prefix2: string): [string, string] {
  // Use same timestamp for both to maintain relationship
  const timestamp = Date.now().toString(36);
  const random1 = Math.random().toString(36).substr(2, 9);
  const random2 = Math.random().toString(36).substr(2, 9);
  
  return [
    `temp_${prefix1}_${timestamp}_${random1}`,
    `temp_${prefix2}_${timestamp}_${random2}`
  ];
}

/**
 * Check if an ID is a temporary ID generated by this utility
 * @param id - ID to check
 * @returns True if ID starts with 'temp_'
 */
export function isTempId(id: string): boolean {
  return id.startsWith('temp_');
}
