#!/usr/bin/env python
# -*- coding: utf-8 -*-

"""
Simple code executor module for running script code generated by LLM agents.
"""

import asyncio
from typing import Any, Dict, Optional
from pydantic import BaseModel
import io
import contextlib
import multiprocessing as mp
import sys
import traceback
import time

# Import the logger
from aicore.agents.code_executor.logger import get_logger

# Get logger for this module
logger = get_logger()

# Default timeout for code execution in seconds
DEFAULT_TIMEOUT = 30

class CodeExecutionResult(BaseModel):
    """Model for code execution results, including stdout/stderr"""
    result: Any
    stdout: Optional[str] = None
    stderr: Optional[str] = None
    status: str = "success"
    error: Optional[str] = None

def process_executor(code_string, result_queue):
    """Function to run in separate process"""
    # Capture stdout and stderr
    stdout_capture = io.StringIO()
    stderr_capture = io.StringIO()
    
    # Prepare result dictionary
    result_data = {
        "result": None,
        "stdout": "",
        "stderr": "",
        "status": "success",
        "error": None
    }
    
    try:
        # Create namespace for execution
        namespace = {'__builtins__': __builtins__}
        
        # Redirect stdout/stderr and execute
        with contextlib.redirect_stdout(stdout_capture), contextlib.redirect_stderr(stderr_capture):
            exec(code_string, namespace, namespace)
            
            # Retrieve result variable
            result_data["result"] = namespace.get('result', None)
            result_data["stdout"] = stdout_capture.getvalue()
            result_data["stderr"] = stderr_capture.getvalue()
            
            if 'result' in namespace:
                logger.debug("Script executed, found 'result' variable.")
            else:
                logger.debug("Script executed, 'result' variable not found.")
            
    except Exception as e:
        # Capture exception details
        result_data["status"] = "error"
        result_data["error"] = str(e)
        result_data["stderr"] += f"\n{traceback.format_exc()}"
        logger.error(f"Error during code execution: {e}")
    
    finally:
        # Add final stdout/stderr content
        if not result_data["stdout"]:
            result_data["stdout"] = stdout_capture.getvalue()
        if not result_data["stderr"]:
            result_data["stderr"] = stderr_capture.getvalue()
        
        # Send result back through queue
        result_queue.put(result_data)
        
        # Close StringIO objects
        stdout_capture.close()
        stderr_capture.close()

def _execute(code_string: str) -> Dict[str, Any]:
    """
    Legacy function for synchronous execution. 
    Replaced by process-based execution.
    """
    # Create a shared namespace for execution (used for both globals and locals)
    # Initialize with Python's builtins to allow normal Python operations
    namespace = {'__builtins__': __builtins__}
    
    stdout_capture = io.StringIO()
    stderr_capture = io.StringIO()
    
    exec_result = None
    exec_stdout = ""
    exec_stderr = ""

    try:
        # Redirect stdout/stderr and execute the code
        # Use the same namespace for both globals and locals to ensure
        # imports and function definitions work correctly
        with contextlib.redirect_stdout(stdout_capture), contextlib.redirect_stderr(stderr_capture):
            exec(code_string, namespace, namespace)
        
        # Retrieve stdout/stderr
        exec_stdout = stdout_capture.getvalue()
        exec_stderr = stderr_capture.getvalue()

        # Attempt to retrieve the value of the 'result' variable
        exec_result = namespace.get('result', None)
        
        if 'result' in namespace:
             logger.debug("Script executed, found 'result' variable.")
        else:
             logger.debug("Script executed, 'result' variable not found.")
        
        if exec_stdout:
            logger.debug(f"Captured stdout: {exec_stdout.strip()}")
        if exec_stderr:
            logger.debug(f"Captured stderr: {exec_stderr.strip()}")
            
    except Exception as e:
        logger.error(f"Error during code execution: {e}")
        # Capture any remaining stderr output from the exception itself
        exec_stderr += stderr_capture.getvalue()
        # Reraise the exception to be caught by execute_code_string
        raise
    finally:
        # Ensure String IO buffers are closed
        stdout_capture.close()
        stderr_capture.close()

    return {"result": exec_result, "stdout": exec_stdout, "stderr": exec_stderr}

def execute_in_process(code_string: str, timeout: int) -> Dict[str, Any]:
    """
    Execute code in a separate process with proper timeout handling.
    
    Args:
        code_string: String containing the Python script.
        timeout: Maximum execution time in seconds.
        
    Returns:
        Dictionary containing execution results.
    """
    # Create a queue for results
    result_queue = mp.Queue()
    
    # Create and start process
    process = mp.Process(
        target=process_executor,
        args=(code_string, result_queue),
        daemon=True
    )
    
    start_time = time.time()
    logger.debug(f"Starting process execution with timeout {timeout}s")
    process.start()
    
    # Wait for process to complete or timeout
    process.join(timeout)
    elapsed = time.time() - start_time
    
    if process.is_alive():
        # Process is still running after timeout
        logger.warning(f"Code execution timed out after {timeout} seconds, terminating process")
        process.terminate()
        # Force kill if needed after a short grace period
        process.join(0.5)
        if process.is_alive():
            logger.warning("Process didn't terminate gracefully, forcing kill")
            if hasattr(process, "kill"):  # Python 3.7+
                process.kill()
        
        return {
            "result": None,
            "stdout": "",
            "stderr": f"Code execution timed out after {timeout} seconds and was terminated.",
            "status": "error",
            "error": f"Execution timed out after {timeout} seconds"
        }
    
    logger.debug(f"Process completed in {elapsed:.2f} seconds")
    
    # Process completed, get results from queue
    if not result_queue.empty():
        result_data = result_queue.get()
        return result_data
    else:
        # Process exited but didn't put anything in queue
        logger.error("Process terminated without returning results")
        return {
            "result": None,
            "stdout": "",
            "stderr": "Process terminated without returning results",
            "status": "error",
            "error": "No results returned from execution process"
        }

async def execute_async(code_string: str, timeout: int) -> Dict[str, Any]:
    """
    Execute LLM-generated code string in an async context with proper timeout.
    
    Args:
        code_string: String containing the Python script.
        timeout: Maximum execution time in seconds.
        
    Returns:
        Dictionary containing 'result', 'stdout', and 'stderr'.
    """
    loop = asyncio.get_event_loop()
    
    # Use process-based execution with proper timeout handling
    return await loop.run_in_executor(None, lambda: execute_in_process(code_string, timeout))

async def execute_code_string(code: str, timeout: int = DEFAULT_TIMEOUT) -> CodeExecutionResult:
    """
    Execute a code string and return a structured result including stdout/stderr.
    Assumes the code assigns its output to a variable named 'result'.
    
    Args:
        code: String containing Python script to execute.
        timeout: Maximum execution time in seconds (default: 30).
        
    Returns:
        A CodeExecutionResult object with result, stdout, stderr, or error.
    """
    try:
        # Execute code in process with timeout
        result_data = await execute_async(code, timeout)
        
        # Log results
        logger.info(
            f"Code execution complete. Status: {result_data.get('status')}, "
            f"Result: {result_data.get('result')}, "
            f"Stdout: '{result_data.get('stdout', '').strip()}', "
            f"Stderr: '{result_data.get('stderr', '').strip()}'"
        )
        
        # Return structured result
        return CodeExecutionResult(
            result=result_data.get('result'),
            stdout=result_data.get('stdout', ''),
            stderr=result_data.get('stderr', ''),
            status=result_data.get('status', 'success'),
            error=result_data.get('error')
        )
    except Exception as e:
        # Handle any unexpected exceptions during execution
        error_msg = str(e)
        logger.error(f"Unexpected error during code execution: {error_msg}")
        return CodeExecutionResult(
            result=None,
            stdout="",
            stderr=f"Error during execution: {error_msg}\n{traceback.format_exc()}",
            status="error",
            error=error_msg
        )
