import os
import uuid
from typing import Dict, List, Any, Optional
from agents import Agent, RunContextWrapper, WebSearchTool, function_tool
from aicore.code_executor.new_code_tool import execute_code_func, execute_system_command_func, CodeExecutionResult, SystemCommandResult, DEFAULT_TIMEOUT
from aicore.code_executor.logger import get_logger
from aicore.prompt_utils import get_instructions_template, INITIAL_CORE_PROMPT

# Get logger with class-specific name
logger = get_logger("HTTPCodeExecutorAgent")

class HTTPCodeExecutorAgent(Agent):
    """
    HTTP-based Code Executor Agent for FastAPI server execution.
    
    This agent uses HTTP-based code execution with automatic file downloading.
    No local file management - all files are handled via HTTP API calls.
    Files generated by tool executions are automatically tracked by message ID with full metadata.
    """
    
    def __init__(self, name: str, core_prompt: str = INITIAL_CORE_PROMPT, model: str = "gpt-4o-mini-2024-07-18"):
        """
        Initialize the HTTP Code Executor Agent.
        
        Args:
            name: The name of the agent
            core_prompt: Core prompt for the agent
            model: Model to use for the agent
        """
        self.core_prompt = core_prompt
        
        # Track downloaded files with metadata from HTTP executions by message ID
        # Structure: {message_id: {filename: {content: bytes, download_url: str, size: int, mime_type: str, created_at: str}}}
        self.downloaded_files_by_message: Dict[str, Dict[str, Dict[str, Any]]] = {}
        
        # Current message ID for the agent
        self.current_message_id = str(uuid.uuid4())[:8]
        
        # Get instructions template for HTTP-based execution
        self.instructions_template = get_instructions_template("outputs", core_prompt=self.core_prompt)
        
        # Initialize web search tool
        websearch_tool = WebSearchTool(user_location={"type": "approximate", "city": "New Delhi"})
        
        # Create wrapped tools that auto-capture files
        execute_code_wrapper = self._create_execute_code_wrapper()
        execute_system_command_wrapper = self._create_execute_system_command_wrapper()
        
        # Initialize the parent Agent class with wrapped tools
        super().__init__(
            name=name,
            instructions=self._get_dynamic_instructions,
            tools=[execute_code_wrapper, execute_system_command_wrapper, websearch_tool],
            model=model
        )
    
    def _get_dynamic_instructions(self, run_context: RunContextWrapper, agent: Agent) -> str:
        """
        Dynamically generate instructions with the current message ID.
        
        Args:
            run_context: The current run context
            agent: The agent instance
            
        Returns:
            str: Instructions with the message ID injected
        """
        return self.instructions_template.replace("{message_id}", self.current_message_id)
    
    def set_message_id(self, message_id=None):
        """
        Set the message ID for the next execution.
        
        Args:
            message_id: Custom message ID to use, or None to generate a new one
            
        Returns:
            str: The message ID that was set
        """
        if message_id is None:
            message_id = str(uuid.uuid4())[:8]
        
        self.current_message_id = message_id
        logger.info(f"Set message ID: {message_id}")
        return message_id
        
    def add_downloaded_files(self, message_id: str, downloaded_files: Dict[str, Dict[str, Any]]):
        """
        Add downloaded files with metadata from HTTP execution results.
        
        Args:
            message_id: Message ID associated with the files
            downloaded_files: Dictionary mapping filename -> {content: bytes, download_url: str, size: int, mime_type: str, created_at: str}
        """
        if message_id not in self.downloaded_files_by_message:
            self.downloaded_files_by_message[message_id] = {}
        
        self.downloaded_files_by_message[message_id].update(downloaded_files)
        logger.info(f"Added {len(downloaded_files)} downloaded files with metadata for message {message_id}")
        
        # Log download URLs for each file
        for filename, file_metadata in downloaded_files.items():
            download_url = file_metadata.get("download_url", "")
            if download_url:
                logger.info(f" File {filename} downloaded from {download_url}")
        
    def get_all_plots_with_message_id(self) -> Dict[str, List[str]]:
        """
        Extract all message IDs from downloaded files along with plot filenames.
        Returns a dictionary mapping each message ID to a list of its associated plot filenames.
        
        Returns:
            Dict mapping message_id -> list of plot filenames
        """
        data: Dict[str, List[str]] = {}
        
        for message_id, files in self.downloaded_files_by_message.items():
            # Filter for image/plot files
            plot_files = [filename for filename in files.keys() 
                         if filename.lower().endswith(('.png', '.jpg', '.jpeg', '.svg', '.pdf', '.gif'))]
            if plot_files:
                data[message_id] = sorted(plot_files)
                
        logger.info(f"Found plots for {len(data)} messages")
        return data
    
    def get_downloaded_files_for_message(self, message_id: str) -> Dict[str, bytes]:
        """
        Get all downloaded file contents for a specific message (backwards compatibility).
        
        Args:
            message_id: The message ID to get files for
            
        Returns:
            Dictionary mapping filename -> file content (bytes)
        """
        files_metadata = self.downloaded_files_by_message.get(message_id, {})
        return {filename: metadata["content"] for filename, metadata in files_metadata.items()}
    
    def get_file_metadata_for_message(self, message_id: str) -> Dict[str, Dict[str, Any]]:
        """
        Get all downloaded file metadata for a specific message.
        
        Args:
            message_id: The message ID to get files for
            
        Returns:
            Dictionary mapping filename -> file metadata dict {content: bytes, download_url: str, size: int, mime_type: str, created_at: str}
        """
        return self.downloaded_files_by_message.get(message_id, {})
    
    def get_download_urls_for_message(self, message_id: str) -> Dict[str, str]:
        """
        Get download URLs for all files in a specific message.
        
        Args:
            message_id: The message ID to get URLs for
            
        Returns:
            Dictionary mapping filename -> download URL
        """
        files_metadata = self.downloaded_files_by_message.get(message_id, {})
        return {filename: metadata.get("download_url", "") for filename, metadata in files_metadata.items()}
    
    def get_all_downloaded_files(self) -> Dict[str, Dict[str, bytes]]:
        """
        Get all downloaded file contents across all messages (backwards compatibility).
        
        Returns:
            Dictionary mapping message_id -> {filename -> file content}
        """
        result = {}
        for message_id, files_metadata in self.downloaded_files_by_message.items():
            result[message_id] = {filename: metadata["content"] for filename, metadata in files_metadata.items()}
        return result
        
    def get_current_message_id(self) -> str:
        """
        Get the current message ID.
        
        Returns:
            str: The current message ID
        """
        return self.current_message_id
    
    def clear_downloaded_files(self, message_id: str = None):
        """
        Clear downloaded files for a specific message or all messages.
        
        Args:
            message_id: Specific message ID to clear, or None to clear all
        """
        if message_id is None:
            self.downloaded_files_by_message.clear()
            logger.info("Cleared all downloaded files")
        elif message_id in self.downloaded_files_by_message:
            del self.downloaded_files_by_message[message_id]
            logger.info(f"Cleared downloaded files for message {message_id}")
    
    def get_stats(self) -> Dict[str, int]:
        """
        Get statistics about downloaded files.
        
        Returns:
            Dictionary with statistics
        """
        total_files = sum(len(files) for files in self.downloaded_files_by_message.values())
        total_size = sum(
            metadata.get("size", 0) for files in self.downloaded_files_by_message.values() 
            for metadata in files.values()
        )
        
        return {
            "total_messages": len(self.downloaded_files_by_message),
            "total_files": total_files,
            "total_size_bytes": total_size,
            "messages_with_plots": len(self.get_all_plots_with_message_id())
        }

    def _create_execute_code_wrapper(self):
        """Create a wrapper function for execute_code that captures downloaded files with metadata."""
        
        # Capture reference to self for the closure
        agent = self
        
        @function_tool(strict_mode=False)
        async def execute_code_with_tracking(
            code: str, 
            files: Optional[List[tuple]] = None, 
            timeout: int = DEFAULT_TIMEOUT, 
            download_files: bool = True,  # Agent explicitly enables file downloading for tracking
            *args: Any, 
            **kwargs: Any
        ) -> CodeExecutionResult:
            """
            Execute Python code via secure HTTP FastAPI server with automatic file tracking.
            
            This tool automatically captures any downloaded files and adds them to the
            agent's tracking system using the current message ID, preserving full metadata
            including download URLs.
            
            Args:
                code: Python code to execute
                files: Optional list of (filename, content) tuples to upload
                timeout: Execution timeout in seconds
                download_files: Whether to download generated files (default: True for agent tracking)
                *args: Additional args passed to execute_code
                **kwargs: Additional kwargs passed to execute_code
                
            Returns:
                CodeExecutionResult with execution results and downloaded files
            """
            logger.info(f"Agent executing code with auto file tracking (message: {agent.current_message_id})")
            
            # Call the original execute_code tool from new_code_tool with explicit download_files=True
            result = await execute_code_func(code, files, timeout, download_files, *args, **kwargs)
            
            # Automatically add downloaded files with metadata to agent tracking
            if result.downloaded_files:
                agent.add_downloaded_files(agent.current_message_id, result.downloaded_files)
                logger.info(f"Auto-captured {len(result.downloaded_files)} files with metadata for message {agent.current_message_id}")
            else:
                logger.info(f"No files generated for message {agent.current_message_id}")
            
            return result
        
        return execute_code_with_tracking
    
    def _create_execute_system_command_wrapper(self):
        """Create a wrapper function for execute_system_command for consistency."""
        
        @function_tool(strict_mode=False)
        async def execute_system_command_with_tracking(
            command: str, 
            allowed_prefixes: Optional[List[str]] = None
        ) -> SystemCommandResult:
            """
            Execute system command via secure HTTP FastAPI server.
            
            Args:
                command: System command to execute
                allowed_prefixes: List of allowed command prefixes for security
                
            Returns:
                SystemCommandResult with command execution results
            """
            logger.info(f"Agent executing system command: {command}")
            
            # Call the original execute_system_command tool from new_code_tool
            result = await execute_system_command_func(command, allowed_prefixes)
            
            # System commands don't generate downloadable files, but log for completeness
            logger.info(f"System command completed with status: {result.status}")
            
            return result
        
        return execute_system_command_with_tracking
