import os
import uuid
from typing import Dict, List, Any, Optional
from dataclasses import dataclass, field
from datetime import datetime
from agents import Agent, RunContextWrapper, WebSearchTool, function_tool
from aicore.code_executor.new_code_tool import execute_code_func, execute_system_command_func, CodeExecutionResult, SystemCommandResult, DEFAULT_TIMEOUT
from aicore.code_executor.logger import get_logger
from aicore.prompt_utils import get_instructions_template, INITIAL_CORE_PROMPT
from aicore.code_executor.data_models import DownloadedFilesTracker

# Get logger with class-specific name
logger = get_logger("HTTPCodeExecutorAgent")
class HTTPCodeExecutorAgent(Agent):
    """
    HTTP-based Code Executor Agent for FastAPI server execution.
    
    This agent uses HTTP-based code execution with automatic file downloading.
    No local file management - all files are handled via HTTP API calls.
    Files generated by tool executions are automatically tracked by message ID with full metadata
    using structured classes for better type safety and organization.
    
    File Tracking Architecture:
        - FileMetadata: Individual file with content, URL, size, mime_type, etc.
        - MessageFiles: Collection of files for a specific message
        - DownloadedFilesTracker: Overall tracking across all messages
    
    Modes:
        should_download_files=True:  Downloads file content + tracks URLs/metadata
        should_download_files=False: Tracks URLs/metadata only, no content download
        
    Usage:
        # URL-only mode (lightweight)
        agent = HTTPCodeExecutorAgent("Agent", should_download_files=False)
        await agent.run("Create a plot")
        urls = agent.get_download_urls_for_message(agent.current_message_id)
        
        # Full download mode  
        agent = HTTPCodeExecutorAgent("Agent", should_download_files=True)
        await agent.run("Create a plot")
        
        # Structured access to files
        message_files = agent.file_tracker.get_message_files(agent.current_message_id)
        if message_files:
            plot_files = message_files.get_plot_files()
            content_files = message_files.get_files_with_content()
            url_only = message_files.get_url_only_files()
            stats = message_files.get_stats()
    """
    
    def __init__(self, name: str, core_prompt: str = INITIAL_CORE_PROMPT, 
                model: str = "gpt-4o-mini-2024-07-18", 
                should_download_files: bool = False
                ):
        """
        Initialize the HTTP Code Executor Agent.
        
        Args:
            name: The name of the agent
            core_prompt: Core prompt for the agent
            model: Model to use for the agent
            should_download_files: Whether to download files from the server
        """
        self.core_prompt = core_prompt
        
        self.should_download_files = should_download_files
        
        # Track downloaded files with metadata from HTTP executions by message ID
        self.file_tracker = DownloadedFilesTracker()
        
        # Current message ID for the agent
        self.current_message_id = str(uuid.uuid4())[:8]
        
        # Get instructions template for HTTP-based execution
        self.instructions_template = get_instructions_template("outputs", core_prompt=self.core_prompt)
        
        # Initialize web search tool
        websearch_tool = WebSearchTool(user_location={"type": "approximate", "city": "New Delhi"})
        
        # Create wrapped tools that auto-capture files
        self.execute_code_wrapper = self._create_execute_code_wrapper()
        self.execute_system_command_wrapper = self._create_execute_system_command_wrapper()
        
        # Initialize the parent Agent class with wrapped tools
        super().__init__(
            name=name,
            instructions=self._get_dynamic_instructions,
            tools=[self.execute_code_wrapper, self.execute_system_command_wrapper, websearch_tool],
            model=model
        )
    
    def _get_dynamic_instructions(self, run_context: RunContextWrapper, agent: Agent) -> str:
        """
        Dynamically generate instructions with the current message ID.
        
        Args:
            run_context: The current run context
            agent: The agent instance
            
        Returns:
            str: Instructions with the message ID injected
        """
        return self.instructions_template.replace("{message_id}", self.current_message_id)
    
    def set_message_id(self, message_id=None):
        """
        Set the message ID for the next execution.
        
        Args:
            message_id: Custom message ID to use, or None to generate a new one
            
        Returns:
            str: The message ID that was set
        """
        if message_id is None:
            message_id = str(uuid.uuid4())[:8]
        
        self.current_message_id = message_id
        logger.info(f"Set message ID: {message_id}")
        return message_id
        
    def get_all_plots_with_message_id(self) -> Dict[str, List[str]]:
        """
        Extract all message IDs from downloaded files along with plot filenames.
        Returns a dictionary mapping each message ID to a list of its associated plot filenames.
        
        Returns:
            Dict mapping message_id -> list of plot filenames
        """
        return self.file_tracker.get_plots_by_message()
    
    def get_downloaded_files_for_message(self, message_id: str) -> Dict[str, bytes]:
        """
        Get all downloaded file contents for a specific message.
        Only returns files that have actual content (excludes URL-only files).
        
        Args:
            message_id: The message ID to get files for
            
        Returns:
            Dictionary mapping filename -> file content (bytes)
        """
        return self.file_tracker.get_file_contents_for_message(message_id)
    
    def get_file_metadata_for_message(self, message_id: str) -> Dict[str, Dict[str, Any]]:
        """
        Get all file metadata for a specific message.
        Includes both downloaded and URL-only files.
        
        Args:
            message_id: The message ID to get files for
            
        Returns:
            Dictionary mapping filename -> file metadata dict
        """
        return self.file_tracker.get_file_metadata_for_message(message_id)
    
    def get_download_urls_for_message(self, message_id: str) -> Dict[str, str]:
        """
        Get download URLs for all files in a specific message.
        
        Args:
            message_id: The message ID to get URLs for
            
        Returns:
            Dictionary mapping filename -> download URL
        """
        return self.file_tracker.get_download_urls_for_message(message_id)
    
    def get_all_downloaded_files(self) -> Dict[str, Dict[str, bytes]]:
        """
        Get all downloaded file contents across all messages.
        Only returns files that have actual content (excludes URL-only files).
        
        Returns:
            Dictionary mapping message_id -> {filename -> file content}
        """
        return self.file_tracker.get_all_file_contents()
        
    def has_files_with_content(self, message_id: str = None) -> bool:
        """
        Check if files have actual content (not just URLs).
        
        Args:
            message_id: Check specific message, or None to check all messages
            
        Returns:
            True if there are files with content, False otherwise
        """
        return self.file_tracker.has_files_with_content(message_id)
    
    def get_file_counts(self, message_id: str = None) -> Dict[str, int]:
        """
        Get counts of files with content vs URL-only files.
        
        Args:
            message_id: Check specific message, or None for all messages
            
        Returns:
            Dict with 'with_content' and 'url_only' counts
        """
        return self.file_tracker.get_file_counts(message_id)
        
    def get_current_message_id(self) -> str:
        """
        Get the current message ID.
        
        Returns:
            str: The current message ID
        """
        return self.current_message_id
    
    def clear_downloaded_files(self, message_id: str = None):
        """
        Clear downloaded files for a specific message or all messages.
        
        Args:
            message_id: Specific message ID to clear, or None to clear all
        """
        self.file_tracker.clear_message(message_id)
    
    def get_stats(self) -> Dict[str, int]:
        """
        Get statistics about downloaded files.
        
        Returns:
            Dictionary with statistics
        """
        return self.file_tracker.get_overall_stats()
    
    def _create_execute_code_wrapper(self):
        """Create a wrapper function for execute_code that captures downloaded files with metadata."""
        
        # Capture reference to self for the closure
        _agent = self
        _download_files = _agent.should_download_files
        
        @function_tool(strict_mode=False)
        async def execute_code_with_tracking(
            code: str, 
            files: Optional[List[tuple]] = None, 
            timeout: int = DEFAULT_TIMEOUT,  # Agent explicitly enables file downloading for tracking
            *args: Any, 
            **kwargs: Any
        ) -> CodeExecutionResult:
            """
            Execute Python code via secure HTTP FastAPI server with automatic file tracking.
            
            This tool automatically captures any downloaded files and adds them to the
            agent's tracking system using the current message ID, preserving full metadata
            including download URLs.
            
            Args:
                code: Python code to execute
                files: Optional list of (filename, content) tuples to upload
                timeout: Execution timeout in seconds
                download_files: Whether to download generated files (default: True for agent tracking)
                *args: Additional args passed to execute_code
                **kwargs: Additional kwargs passed to execute_code
                
            Returns:
                CodeExecutionResult with execution results and downloaded files
            """
            logger.info(f"Agent executing code with auto file tracking (message: {_agent.current_message_id})")
            logger.info(f"Download mode: {'ENABLED' if _download_files else 'DISABLED'} (URLs only)")
            
            # Call the original execute_code tool from new_code_tool with explicit download_files=True
            result = await execute_code_func(code, files, timeout, _download_files, *args, **kwargs)
            
            # Handle file tracking based on what we got back
            if result.downloaded_files:
                # Files were downloaded with content
                _agent.file_tracker.add_message_files(_agent.current_message_id, result.downloaded_files)
                logger.info(f"Auto-captured {len(result.downloaded_files)} files with content for message {_agent.current_message_id}")
            elif result.output_files:
                # Files exist but weren't downloaded (URLs only)
                _agent.file_tracker.add_output_files(_agent.current_message_id, result.output_files)
                logger.info(f"Auto-captured {len(result.output_files)} files (URLs only) for message {_agent.current_message_id}")
            else:
                logger.info(f"No files generated for message {_agent.current_message_id}")
            
            return result
        
        return execute_code_with_tracking
    
    def _create_execute_system_command_wrapper(self):
        """Create a wrapper function for execute_system_command for consistency."""
        
        @function_tool(strict_mode=False)
        async def execute_system_command_with_tracking(
            command: str, 
            allowed_prefixes: Optional[List[str]] = None
        ) -> SystemCommandResult:
            """
            Execute system command via secure HTTP FastAPI server.
            
            Args:
                command: System command to execute
                allowed_prefixes: List of allowed command prefixes for security
                
            Returns:
                SystemCommandResult with command execution results
            """
            logger.info(f"Agent executing system command: {command}")
            
            # Call the original execute_system_command tool from new_code_tool
            result = await execute_system_command_func(command, allowed_prefixes)
            
            # System commands don't generate downloadable files, but log for completeness
            logger.info(f"System command completed with status: {result.status}")
            
            return result
        
        return execute_system_command_with_tracking
